#:kivy 1.11.1

<TrailsView>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 10
        padding: 10

        Label:
            text: 'Treasure Trails'
            # halign: left
        TextInput:
            size_hint: (.8, None)
            text: 'Enter clue'
            multiline: False
            height: self.minimum_height
        Label:
            text: 'hi '
        Label:
            text: 'there'